spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sisko_exam?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: P@ssW0rd32!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Jakarta
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Jakarta

server:
  port: 8080

app:
  jwt:
    secret: K8y2KYfZKobypjZMDCr5Xg/eRAjf+lHTPf6J5K16OjVq/5SMjk4n8iql98KQ+4vbCvL6Orzs3QLJH00bb35duA==
    exp-minutes: 3600000 #1 hour
    refresh-minutes: 86400000 #24 hours

logging:
  level:
    root: INFO
    com.exam.exam: INFO
  file:
    name: logs/app.log # will be overridden by logback-spring.xml policies